/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;
import magick.*;

public class App {
public String getGreeting() {
        return "Hello world.";
}

public static void main(String[] args) throws MagickException {
        System.out.println(new App().getGreeting());

        //Data to embed
        byte[] mySecret = "drink your ovaltine".getBytes();

        MagickImage img = new MagickImage(new ImageInfo("basn6a16.png"));


        System.out.println(img.getImageFormat());
        //getOnePixel(int x, int y)

        //ImageProcessor.embedData(img, mySecret); //mutator

        img.writeImage(new ImageInfo("output.png"));
}
}
