/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.io.File;

public class App {
public String getGreeting() {
        return "Hello world.";
}

public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        //Data to embed
        byte[] mySecret = "drink your ovaltine".getBytes();

        // ImageBuffer img = null;
        //
        // try {
        //         img = ImageIO.read(new File("strawberry.jpg"));
        // } catch (IOException e) {
        //         //
        // }
        //
        // PngWriter out = new PngWriter(new File("test_image_embed.png"), )
}
}
